import { escapeMarkdown, heading } from './markdown/markdown.js';
import { generateDocumentFilename } from './formatter/filename.js';
import { renderProblemSection } from './templates/problemSection.js';
import { renderSolutionSection } from './templates/solutionSection.js';
import { renderComplexitySection } from './templates/complexitySection.js';
import { renderReviewSection } from './templates/reviewSection.js';
import { renderLearningSection, renderPersonalReview } from './templates/learningSection.js';
import type { DocumentGenerationInput, GeneratedDocument } from './types.js';

/**
 * The single place that turns a problem + submission + `CombinedSolutionReview`
 * (Phase 4's deterministic analysis, Phase 5's AI review, and their
 * agreement) into a complete Markdown learning document. Nothing outside
 * `document/` builds Markdown — `controllers/documents.controller.ts` only
 * ever calls this and hands the result to the client, per the task's
 * "do not generate Markdown inside controllers" requirement. See
 * docs/document-generation.md for the full document schema.
 */
export function generateDocument(input: DocumentGenerationInput): GeneratedDocument {
  const { problem, submission, review } = input;

  // submission.code is guaranteed non-null by the time this is called —
  // buildCombinedReview() (services/combined-review.service.ts) already
  // guards this before it ever gets far enough to call analyzeSolution()
  // or the AI provider, both of which require non-null code. Re-asserted
  // here (not silently coerced) so a caller that skips that guard fails
  // loudly instead of generating a document with a missing code section.
  if (submission.code === null) {
    throw new Error('Cannot generate a document for a submission with no code.');
  }

  const title = heading(
    1,
    `LeetCode Problem: ${escapeMarkdown(problem.title ?? problem.slug ?? 'Untitled Problem')}`,
  );

  const sections = [
    title,
    renderProblemSection(problem, submission, review.ai.problemSummary),
    renderSolutionSection(
      submission.code,
      submission,
      review.ai,
      { patterns: review.deterministic.detectedPatterns.map((p) => p.pattern) },
      review.agreement,
    ),
    renderComplexitySection(submission, review.deterministic, review.ai, review.agreement),
    renderReviewSection(submission, review.ai),
    renderLearningSection(review.deterministic, review.ai),
    renderPersonalReview(review.deterministic, review.ai, review.agreement),
    renderFooter(review.submissionId, review.generatedAt),
  ];

  const content = `${sections.join('\n\n')}\n`;
  const filename = generateDocumentFilename({
    slug: problem.slug,
    number: problem.number,
    title: problem.title,
  });

  return { filename, content };
}

function renderFooter(submissionId: string, generatedAt: string): string {
  return [
    '---',
    `_Generated by CodeReviewAI on ${generatedAt}. Submission ID: \`${submissionId}\`._`,
  ].join('\n');
}
